#!/usr/bin/env python3
# Copyright (C) 2026, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

"""Render and execute the supported headless Vitis v0.1 flows.

The runner accepts structured JSON only. It never executes command strings from
an agent; it constructs the allow-listed ``vitis -s`` and ``v++`` argv forms.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import jsonschema


ROOT = Path(__file__).resolve().parents[1]
PLAN_SCHEMA = ROOT / "contracts" / "vitis-execution-plan.schema.json"
RESULT_SCHEMA = ROOT / "contracts" / "vitis-result.schema.json"


def read_json(path: Path) -> dict:
    return json.loads(path.read_text())


def write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def validate_json(instance: dict, schema_path: Path) -> list[str]:
    schema = read_json(schema_path)
    validator = jsonschema.validators.validator_for(schema)(schema)
    return [
        f"{'/'.join(str(item) for item in error.absolute_path) or '<root>'}: {error.message}"
        for error in sorted(
            validator.iter_errors(instance),
            key=lambda item: list(item.absolute_path),
        )
    ]


def resolve_path(value: str, base: Path) -> Path:
    path = Path(value)
    return path.resolve() if path.is_absolute() else (base / path).resolve()


def portable_path(path: Path, base: Path) -> str:
    try:
        return str(path.relative_to(base))
    except ValueError:
        return str(path)


def generated_application_script(plan: dict, base: Path, manifest: Path) -> str:
    embedded = plan["embedded"]
    assert embedded is not None
    config = {
        "request_id": plan["request_id"],
        "xsa": str(resolve_path(embedded["xsa"], base)),
        "workspace": str(resolve_path(embedded["workspace"], base)),
        "platform_name": embedded["platform_name"],
        "cpu": embedded["cpu"],
        "os": embedded["os"],
        "domain": embedded["domain"],
        "generate_dtb": embedded["generate_dtb"],
        "application_name": embedded["application_name"],
        "template": embedded["template"],
        "source_directory": (
            str(resolve_path(embedded["source_directory"], base))
            if embedded["source_directory"] is not None
            else None
        ),
        "source_files": embedded["source_files"],
        "sysroot": (
            str(resolve_path(embedded["sysroot"], base))
            if embedded["sysroot"] is not None
            else None
        ),
        "manifest": str(manifest),
    }
    return f'''#!/usr/bin/env python3
"""Generated by scripts/vitis_runner.py; edit the execution plan, not this file."""

import json
import shutil
from pathlib import Path

import vitis


CONFIG = {config!r}


def main():
    workspace = Path(CONFIG["workspace"])
    marker = workspace / ".vitis-runner-owned"
    if workspace.exists():
        if not marker.is_file() or marker.read_text().strip() != CONFIG["request_id"]:
            raise RuntimeError(f"refusing to replace unowned Vitis workspace: {{workspace}}")
        shutil.rmtree(workspace)
    workspace.mkdir(parents=True)
    marker.write_text(CONFIG["request_id"] + "\\n")

    try:
        client = vitis.create_client()
        client.set_workspace(path=str(workspace))
        platform = client.create_platform_component(
            name=CONFIG["platform_name"],
            hw_design=CONFIG["xsa"],
            cpu=CONFIG["cpu"],
            os=CONFIG["os"],
            domain_name=CONFIG["domain"],
            generate_dtb=CONFIG["generate_dtb"],
        )
        platform.build()
        xpfm = client.find_platform_in_repos(CONFIG["platform_name"])
        app = client.create_app_component(
            name=CONFIG["application_name"],
            platform=xpfm,
            domain=CONFIG["domain"],
            template=CONFIG["template"],
        )
        if CONFIG["source_directory"] is not None:
            app.import_files(
                from_loc=CONFIG["source_directory"],
                files=CONFIG["source_files"],
                dest_dir_in_cmp="src",
            )
        if CONFIG["sysroot"] is not None:
            app.set_sysroot(CONFIG["sysroot"])
        app.build(target="hw")

        elf_files = sorted(str(path) for path in workspace.rglob("*.elf"))
        xpfm_files = sorted(str(path) for path in workspace.rglob("*.xpfm"))
        dtb_files = sorted(str(path) for path in workspace.rglob("*.dtb"))
        Path(CONFIG["manifest"]).parent.mkdir(parents=True, exist_ok=True)
        Path(CONFIG["manifest"]).write_text(
            json.dumps(
                {{
                    "xpfm": xpfm_files,
                    "elf": elf_files,
                    "dtb": dtb_files,
                }},
                indent=2,
                sort_keys=True,
            )
            + "\\n"
        )
        if not xpfm_files:
            raise RuntimeError("platform build produced no XPFM")
        if not elf_files:
            raise RuntimeError("application build produced no ELF")
    finally:
        vitis.dispose()


if __name__ == "__main__":
    main()
'''


def stage(
    stage_id: str,
    owner: str,
    argv: list[str],
    cwd: Path,
    log: Path,
    timeout_seconds: int,
    outputs: list[tuple[str, Path]],
) -> dict:
    return {
        "id": stage_id,
        "owner": owner,
        "argv": argv,
        "cwd": cwd,
        "log": log,
        "timeout_seconds": timeout_seconds,
        "outputs": outputs,
    }


def render(plan: dict, plan_path: Path, generated_dir: Path) -> tuple[list[dict], Path | None]:
    base = plan_path.parent.resolve()
    generated_dir.mkdir(parents=True, exist_ok=True)
    logs = generated_dir / "logs"
    logs.mkdir(parents=True, exist_ok=True)
    toolchain = plan["toolchain"]
    vitis = str(resolve_path(toolchain["vitis"], base))
    vpp = str(resolve_path(toolchain["vpp"], base))
    stages: list[dict] = []

    acceleration = plan["acceleration"]
    if acceleration is not None:
        for compile_plan in acceleration["compile"]:
            argv = [
                vpp,
                "--compile",
                "--mode",
                compile_plan["mode"],
                "--target",
                compile_plan["target"],
                "--config",
                str(resolve_path(compile_plan["config"], base)),
            ]
            if compile_plan["part"] is not None:
                argv.extend(["--part", compile_plan["part"]])
            if compile_plan["platform"] is not None:
                argv.extend(
                    ["--platform", str(resolve_path(compile_plan["platform"], base))]
                )
            output = resolve_path(compile_plan["output"], base)
            argv.extend(["--output", str(output)])
            argv.extend(str(resolve_path(item, base)) for item in compile_plan["inputs"])
            output_kind = "xo" if compile_plan["mode"] == "hls" else "libadf"
            owner = (
                "vitis_hls_engineer"
                if compile_plan["mode"] == "hls"
                else "vitis_aie_engineer"
            )
            stages.append(
                stage(
                    f"compile-{compile_plan['id']}",
                    owner,
                    argv,
                    base,
                    logs / f"compile-{compile_plan['id']}.log",
                    compile_plan["timeout_seconds"],
                    [(output_kind, output)],
                )
            )

        link = acceleration["link"]
        link_output = resolve_path(link["output"], base)
        argv = [
            vpp,
            "--link",
            "--target",
            link["target"],
            "--platform",
            str(resolve_path(link["platform"], base)),
        ]
        for config in link["configs"]:
            argv.extend(["--config", str(resolve_path(config, base))])
        argv.extend(
            [
                "--save-temps",
                "--temp_dir",
                str(resolve_path(link["temp_directory"], base)),
                "--log_dir",
                str(resolve_path(link["log_directory"], base)),
                "--report_dir",
                str(resolve_path(link["report_directory"], base)),
                "--jobs",
                str(link["jobs"]),
                "--output",
                str(link_output),
            ]
        )
        argv.extend(str(resolve_path(item, base)) for item in link["inputs"])
        link_kind = "xclbin" if link_output.suffix == ".xclbin" else "linked-xsa"
        stages.append(
            stage(
                "link",
                "amd_soc_platform_integrator",
                argv,
                base,
                logs / "link.log",
                link["timeout_seconds"],
                [(link_kind, link_output)],
            )
        )

        package = acceleration["package"]
        if package is not None:
            package_dir = resolve_path(package["output_directory"], base)
            argv = [
                vpp,
                "--package",
                "--target",
                package["target"],
                "--platform",
                str(resolve_path(package["platform"], base)),
                "--package.out_dir",
                str(package_dir),
            ]
            if package["boot_mode"] is not None:
                argv.extend(["--package.boot_mode", package["boot_mode"]])
            argv.append(str(resolve_path(package["input"], base)))
            stages.append(
                stage(
                    "package",
                    "amd_soc_platform_integrator",
                    argv,
                    base,
                    logs / "package.log",
                    package["timeout_seconds"],
                    [("package-directory", package_dir)],
                )
            )

    application_manifest: Path | None = None
    if plan["embedded"] is not None:
        application_script = generated_dir / "build_vitis_application.py"
        application_manifest = generated_dir / "application-artifacts.json"
        application_script.write_text(
            generated_application_script(plan, base, application_manifest)
        )
        application_script.chmod(0o755)
        stages.append(
            stage(
                "embedded-app",
                "vitis_sw_engineer",
                [vitis, "-s", str(application_script)],
                base,
                logs / "embedded-app.log",
                plan["embedded"]["timeout_seconds"],
                [("vitis-python-script", application_script)],
            )
        )
    return stages, application_manifest


def sourced_environment(settings64: Path) -> dict[str, str]:
    command = [
        "bash",
        "--noprofile",
        "--norc",
        "-c",
        'source "$1" >/dev/null && env -0',
        "vitis-runner",
        str(settings64),
    ]
    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode:
        message = result.stderr.decode(errors="replace").strip()
        raise RuntimeError(f"failed to source {settings64}: {message}")
    environment: dict[str, str] = {}
    for record in result.stdout.split(b"\0"):
        if not record or b"=" not in record:
            continue
        key, value = record.split(b"=", 1)
        environment[key.decode()] = value.decode(errors="surrogateescape")
    return environment


def artifact_record(kind: str, path: Path, base: Path) -> dict:
    exists = path.is_file() if kind != "package-directory" else path.is_dir()
    return {
        "kind": kind,
        "path": portable_path(path, base),
        "exists": exists,
        "sha256": sha256_file(path) if path.is_file() else None,
    }


def validate_inputs(plan: dict, plan_path: Path) -> list[str]:
    base = plan_path.parent.resolve()
    errors: list[str] = []
    toolchain = plan["toolchain"]
    for field in ("settings64", "vitis", "vpp"):
        path = resolve_path(toolchain[field], base)
        if not path.is_file():
            errors.append(f"toolchain.{field} does not exist: {path}")
    for artifact in plan["input_artifacts"]:
        path = resolve_path(artifact["path"], base)
        if not path.exists():
            errors.append(f"input artifact does not exist: {path}")
        elif artifact["sha256"] is not None and path.is_file():
            actual = sha256_file(path)
            if actual.lower() != artifact["sha256"].lower():
                errors.append(f"input artifact SHA-256 mismatch: {path}")
    return errors


def execute(
    plan: dict,
    plan_path: Path,
    generated_dir: Path,
    result_path: Path,
    dry_run: bool,
) -> int:
    base = plan_path.parent.resolve()
    stages, application_manifest = render(plan, plan_path, generated_dir)
    result = {
        "schema_version": 1,
        "request_id": plan["request_id"],
        "plan_revision": plan["revision"],
        "plan_sha256": sha256_file(plan_path),
        "status": "DRY_RUN" if dry_run else "PASS",
        "toolchain_version": plan["toolchain"]["version"],
        "commands": [],
        "artifacts": [],
        "findings": [],
    }
    write_json(
        generated_dir / "commands.json",
        [
            {
                "id": item["id"],
                "owner": item["owner"],
                "argv": item["argv"],
                "cwd": str(item["cwd"]),
                "log": str(item["log"]),
                "timeout_seconds": item["timeout_seconds"],
            }
            for item in stages
        ],
    )

    def append_skipped_commands() -> None:
        for item in stages:
            result["commands"].append(
                {
                    "id": item["id"],
                    "owner": item["owner"],
                    "argv": item["argv"],
                    "cwd": str(item["cwd"]),
                    "log": portable_path(item["log"], base),
                    "status": "SKIPPED",
                    "exit_code": None,
                    "duration_seconds": 0,
                }
            )

    if dry_run:
        append_skipped_commands()
        for item in stages:
            result["artifacts"].extend(
                artifact_record(kind, path, base) for kind, path in item["outputs"]
            )
        write_json(result_path, result)
        return 0

    input_errors = validate_inputs(plan, plan_path)
    if input_errors:
        result["status"] = "FAIL"
        append_skipped_commands()
        result["findings"].extend(
            {
                "stage": "preflight",
                "severity": "error",
                "message": message,
                "owner": "amd_soc_platform_integrator",
            }
            for message in input_errors
        )
        write_json(result_path, result)
        return 1

    settings64 = resolve_path(plan["toolchain"]["settings64"], base)
    try:
        environment = sourced_environment(settings64)
    except RuntimeError as exc:
        result["status"] = "FAIL"
        append_skipped_commands()
        result["findings"].append(
            {
                "stage": "environment",
                "severity": "error",
                "message": str(exc),
                "owner": "amd_soc_platform_integrator",
            }
        )
        write_json(result_path, result)
        return 1

    failed = False
    for item in stages:
        for _, output in item["outputs"]:
            output.parent.mkdir(parents=True, exist_ok=True)
        item["log"].parent.mkdir(parents=True, exist_ok=True)
        start = time.monotonic()
        exit_code: int
        try:
            with item["log"].open("w") as log:
                completed = subprocess.run(
                    item["argv"],
                    cwd=item["cwd"],
                    env=environment,
                    stdout=log,
                    stderr=subprocess.STDOUT,
                    timeout=item["timeout_seconds"],
                )
            exit_code = completed.returncode
        except subprocess.TimeoutExpired:
            exit_code = 124
            with item["log"].open("a") as log:
                log.write(
                    f"\nERROR: stage exceeded {item['timeout_seconds']} seconds\n"
                )
        duration = round(time.monotonic() - start, 3)
        status = "PASS" if exit_code == 0 else "FAIL"
        result["commands"].append(
            {
                "id": item["id"],
                "owner": item["owner"],
                "argv": item["argv"],
                "cwd": str(item["cwd"]),
                "log": portable_path(item["log"], base),
                "status": status,
                "exit_code": exit_code,
                "duration_seconds": duration,
            }
        )
        result["artifacts"].append(artifact_record("log", item["log"], base))
        result["artifacts"].extend(
            artifact_record(kind, path, base) for kind, path in item["outputs"]
        )
        missing_outputs = [
            str(path)
            for kind, path in item["outputs"]
            if not (
                path.is_dir() if kind == "package-directory" else path.is_file()
            )
        ]
        if exit_code == 0 and missing_outputs:
            failed = True
            result["status"] = "FAIL"
            result["findings"].append(
                {
                    "stage": item["id"],
                    "severity": "error",
                    "message": f"command produced no required outputs: {missing_outputs}",
                    "owner": item["owner"],
                }
            )
            break
        if exit_code:
            failed = True
            result["status"] = "FAIL"
            result["findings"].append(
                {
                    "stage": item["id"],
                    "severity": "error",
                    "message": f"command exited with status {exit_code}",
                    "owner": item["owner"],
                }
            )
            break

    if not failed and application_manifest is not None:
        if not application_manifest.is_file():
            result["status"] = "FAIL"
            result["findings"].append(
                {
                    "stage": "embedded-app",
                    "severity": "error",
                    "message": "Vitis application artifact manifest is missing",
                    "owner": "vitis_sw_engineer",
                }
            )
        else:
            application_artifacts = read_json(application_manifest)
            for kind in ("xpfm", "elf", "dtb"):
                result["artifacts"].extend(
                    artifact_record(kind, Path(path), base)
                    for path in application_artifacts.get(kind, [])
                )

    result_errors = validate_json(result, RESULT_SCHEMA)
    if result_errors:
        print("\n".join(f"ERROR: result {error}" for error in result_errors), file=sys.stderr)
        return 2
    write_json(result_path, result)
    return 0 if result["status"] == "PASS" else 1


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--plan", required=True, type=Path)
    result.add_argument(
        "--generated-dir",
        type=Path,
        help="generated scripts and logs; defaults to <plan-dir>/vitis",
    )
    result.add_argument(
        "--result",
        type=Path,
        help="result JSON; defaults to <plan-dir>/vitis-result.json",
    )
    result.add_argument(
        "--dry-run",
        action="store_true",
        help="render and validate supported commands without invoking Vitis",
    )
    result.add_argument(
        "--validate-only",
        action="store_true",
        help="validate the plan schema without rendering commands",
    )
    return result


def main() -> int:
    args = parser().parse_args()
    plan_path = args.plan.resolve()
    try:
        plan = read_json(plan_path)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    errors = validate_json(plan, PLAN_SCHEMA)
    if errors:
        for error in errors:
            print(f"ERROR: plan {error}", file=sys.stderr)
        return 2
    if args.validate_only:
        return 0
    generated_dir = (
        args.generated_dir.resolve()
        if args.generated_dir
        else plan_path.parent / "vitis"
    )
    result_path = (
        args.result.resolve()
        if args.result
        else plan_path.parent / "vitis-result.json"
    )
    return execute(plan, plan_path, generated_dir, result_path, args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
